name: Continuous Deployment
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 20.x ]
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          always-auth: true
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org/

      - name: Install Dependencies
        run: yarn install

      - name: Compile
        run: yarn build:only

      # Set up Git user identity for committing
      - name: Set up Git for commit
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'

      - name: Bump version
        run: yarn version --patch
      
      - name: Stage version bump
        run: git add package.json yarn.lock

      - name: Commit version bump
        run: |
          git commit -m "ci: bump version to $(cat package.json | jq -r .version)"

      - name: Push changes
        run: git push origin HEAD:${{ github.ref }}

      - name: Publish
        run: npm publish 
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
