name: Continuous Integration

on:
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 20.x ]
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          always-auth: true
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org/

      - name: Install Dependencies
        run: yarn install

      - name: Start Browserless Docker container
        run: |
          docker run -d --name browserless -p 3000:3000 browserless/chrome:latest

      - name: Wait for Browserless to be ready
        run: |
          until curl -s http://localhost:3000/json/version; do echo "Waiting for browserless..."; sleep 3; done

      - name: Run Tests
        run: yarn test
        env:
          BROWSERLESS_HOST: 127.0.0.1
          BROWSERLESS_PORT: 3000

      - name: Version Bump
        run: |
          git config --local user.email "mihnea.dev@gmail.com"
          git config --local user.name "Mihnea Manolache"
          yarn version --patch

      - name: Stop Browserless Docker container
        run: docker stop browserless && docker rm browserless
