name: Version Bump
on:
  push:
    branches:
      - main
jobs:
  version:
    runs-on: ubuntu-latest
    if: "!startsWith(github.event.head_commit.message, '[RELEASE]')"
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GTOKEN }}
      - run: git config --global user.name 'Mihnea.dev'
      - run: git config --global user.email 'me@mihnea.dev'
      - run: npm version patch -m "[RELEASE] %s"
      - run: git push
